version: '3.4'

services:
  simplegrpccacheservice:
    hostname: simplegrpccacheservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
# - ASPNETCORE_HTTP_PORTS=8080
# - ASPNETCORE_HTTPS_PORTS=8081
      - IsServer=true
    ports:
      - "8080"
# - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  simplegrpccacheclient1:
    hostname: simplegrpccacheclient1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  simplegrpccacheclient2:
    hostname: simplegrpccacheclient2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro